package:
  name: pyhessioxxx
  version:

source:
  git_tag:
  git_url: https://github.com/jacquemier/pyhessioxxx.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pyhessioxxx

about:
  home: https://github.com/jacquemier/pyhessioxxx
  license: BSD
  summary: "Python wrapper for CTA Monte Carlo."
