#!/bin/bash

list="HESS_PHASE_1 HESS_PHASE_2 HESS_PHASE_3 \
  CTA CTA_ULTRA CTA_ULTRA=5 CTA_MAX CTA_PROD1 CTA_PROD2 \
  CTA_SC CTA_SC=1 CTA_SC=2 CTA_SC=3 CTA_SC=4 CTA_PROD2_SC CTA_MAX_SC \
  MEGAPIX"

if [ ! -z "$1" ]; then
   list="$@"
fi 

for k in $list; do
   echo ''
   echo '*********************************************************'
   echo '*'
   echo '* Building hessio library for configuration' "$k"
   echo '*'
   echo '*********************************************************'
   echo ''
   make clean
   make EXTRA_DEFINES="-D$k" || exit 1
   echo ''
   echo '* Configuration' "$k" 'successfully built.'
   echo ''
   make EXTRA_DEFINES="-D$k" install
   bin/read_hess -v --version || exit 1
   echo ''
   echo '* Configuration' "$k" 'seems to work.'
   echo ''   
done


